### PR TITLE
HELM-9: Adding optional feature to enable clustering of xwiki application

### PR DESCRIPTION
**Pull request by ASHISH932**
* Configured jgroups
* Mounting JGroups config file through jgroupConfigMaps
* Optional feature to enable clustering

### CODE REVIEW

**Comment by slayerjain** [comment]
JGroup instances aren't able to talk to each other. Since by default JGroup uses Multicast for cluster discovery and many Kubernetes network drivers don't support UDP Multicast, there are other ways to discover JGroup clusters like https://github.com/jgroups-extras/jgroups-kubernetes. This may require some code level change.

**Comment by slayerjain** [comment]
We may merge this for now, since there are other changes which make the chart better. But the issue will still remain open

**Comment by slayerjain** [comment]
@ASHISH932 In the README you should probably warn users that clustering is not complete yet, and also discuss on XWiki about the reason.

**Comment by slayerjain** [comment]
Screenshot 2019-08-29 at 12 46 45 PM

**Comment by slayerjain** [comment]
@ASHISH932 So I think you can try this out ;)

**Comment by ranma2913** [comment]
Any progress on this? I'd love to try this out.

**Comment by slayerjain** [comment]
@ASHISH932 Can you please help with the status of this PR?

**Comment by gsautner** [comment]
This pull request was used as reference for other changes that were made to enable clustering after this helm version [1.2](https://extensions.xwiki.org/xwiki/bin/view/Extension/XWikiHelm/#Hv1.2.0). 

Many thanks for all details and work done that was used as guide for other tasks.

**Pull request closed without merging**
