### PR TITLE
HELM-50: Secrets enabled option

### PR DESCRIPTION
**Pull request by realRunlo**
I have a use case that requires secrets to be disabled, adding this switch allows me to do just that.

### CODE REVIEW

**Comment by gsautner** [comment]
One question, you are creating a custom secret file with the same name? Or you're passing the database password with extra env vars? 

I'm looking logic on [workload](https://github.com/xwiki-contrib/xwiki-helm/blob/master/charts/xwiki/templates/xwiki.yaml#L72), and maybe we don't need to create this file for MySQL and PostgreSQL.

**Comment by realRunlo** [comment]
I'm using sealed secret to generate my secret with the same name, for external db.

Why wouldn't  we need to create  this file for MySQL and PostgreSQL?

**Comment by gsautner** [comment]
> Why wouldn't we need to create this file for MySQL and PostgreSQL?

Looking at this PR, notice that this secret is created but not used in some cases. 

Maybe a good alternative is to have a custom secretKeyRef for the external database password. And create that secret only if custom database is used without this new value reference. I think this can help other users who want to use other database solutions that already generate password on a specific secret to reuse/reference that secrets with proper mapping.

**Comment by realRunlo** [comment]
So this is what you have in mind?:
-  Custom secretkeyRef for external db
-  Create default secret only if custom reference not used 

>  I think this can help other users who want to use other database solutions that already generate password on a specific secret to reuse/reference that secrets with proper mapping

Agree, because right now the secret name is attached to the release name

**Comment by realRunlo** [comment]
So i implemented:
- Custom key reference for external db
- Default external db secret only created if custom key reference disabled

I hope this implementation aligns with your expectations. If any changes are needed, please let me know.

**Comment by realRunlo** [comment]
There is a typo in vaules.yml line 188, should be customKeyRef

**Comment by gsautner** [comment]
I have made some minor changes to be compatible with some testing env. 

If you want to see, check this commit: https://github.com/xwiki-contrib/xwiki-helm/commit/d94a413f9bd23fc868153b2890251d7cd77986de

I'm still finishing some tests, but I believe I'll release version 1.2.4 between today and tomorrow.

Overall, truly grateful for the contributions.

**Pull request merged**
